name: Release
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04

    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
      packages: write # to be able to push to GitHub Container Registry

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Pkl
        uses: pkl-community/setup-pkl@v0
        with:
          pkl-version: "0.27.1"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install --no-install-recommends --no-upgrade -y just shellcheck podman
          
      - name: Install semantic-release dependencies
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          npm install \
            semantic-release \
            @semantic-release/exec \
            @semantic-release/git \
            @semantic-release/github \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator \
            conventional-changelog-conventionalcommits \
            -D

      - name: Run all commit checks
        run: |
          just check-commit

      - name: Run container tests
        run: |
          cd tests && just test

      - name: Build single-file release
        run: just release

      - name: Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      # Container build and push happens after release to ensure tags exist
      - name: Get latest tag
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: latest_tag
        run: |
          # Get the latest tag created by semantic-release
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          echo "tag=${LATEST_TAG}" >> $GITHUB_OUTPUT
          echo "Latest tag: ${LATEST_TAG}"

      - name: Set up Docker Buildx
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.latest_tag.outputs.tag != ''
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.latest_tag.outputs.tag != ''
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for container
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.latest_tag.outputs.tag != ''
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.latest_tag.outputs.tag }}
            type=sha,prefix={{branch}}-

      - name: Build and push container
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.latest_tag.outputs.tag != ''
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Containerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max