name: Release
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04

    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Pkl
        uses: pkl-community/setup-pkl@v0
        with:
          pkl-version: "0.27.1"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install --no-install-recommends --no-upgrade -y just shellcheck podman
          
      - name: Install semantic-release dependencies
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          npm install \
            semantic-release \
            @semantic-release/exec \
            @semantic-release/git \
            @semantic-release/github \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator \
            conventional-changelog-conventionalcommits \
            -D

      - name: Run shellcheck
        run: |
          just shellcheck

      - name: Run Pkl tests
        run: |
          pkl test generate_test.pkl
          pkl test gen_function_test.pkl

      - name: Run generation tests
        run: |
          cd tests && just test-local-generate

      - name: Build release file
        run: |
          just release

      - name: Test release file generation
        run: |
          cd tests && just test-release-generate

      - name: Run container tests
        run: |
          cd tests && just test

      - name: Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release